language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: aAGtmQaU1a4Ky0vtrRf9/mRGT4LCHqmjJR9zIgbwQnDpDI5qRQQPACbwNFBadSGGS3hPTe7Spdt9oaXkf8jZMSjVnDqt7N9OpXIcCP/5zDIFnkxDhJs/Ok2Lsb4AUfmgETjsp80PL6UKPGQKyEvyd4pxM0V6R1BF0Xaid+gbIW1KRtbM7hpsl6Y7pbat4ywCM7cdUEJxWgNbfB/6yhz2WHvHL2LFjC9fuCMgrP2rfcuhJn9WYX6qI1ImTgBlAh1BmvVVxw/i31xOuVOEdLXMpbys5RIK5Yl6CITJ079V1uQC+HqYESri0NvYQUYBTTYS3SdTIGEmxTRvw6Vc9tKfIjC/3MWxSGXdXyQqZYutjQNpQkPo5N2S2gxspEbq37rjXF/WBcODEra0cUurcA7ryh9zzcaFG7j6R88lP6SEO7jbU54ReEfbGkOqtHy3nd8keBslICADzEsxynohast4juEdr9AEa6oK/koCr+tdk9iX6LgBmBPkANN4cBARcrLiHHhqbAuDdRzkmXU0pptteo16XcXNoSXwwLmpMFD5YsyjTyTyOoo3G/+/d9duBc9EUbHkCjVdraP6W/BPcUqzCrrm8oYoC4GcYc15CZEbLaH8hPuDCDKOvaQyHBYsfBNeJmN0hWJTP5LB0Y06bBMyVJ2//nBDupsI+XnFnLvDmtc=
  app: my-restaurants-app